export const DB_GRAPHQL_URL = process.env.REACT_APP_BAGY_GRAPH_DB_URL;
export const LOJAS_TOKENS = {
  LOJA_1_TOKEN: process.env.REACT_APP_LOJA_1_TOKEN,
  LOJA_2_TOKEN: process.env.REACT_APP_LOJA_2_TOKEN,
  LOJA_3_TOKEN: process.env.REACT_APP_LOJA_3_TOKEN,
  LOJA_4_TOKEN: process.env.REACT_APP_LOJA_4_TOKEN,
  LOJA_5_TOKEN: process.env.REACT_APP_LOJA_5_TOKEN,
};
